### ISSUE TITLE
No puedo instalar el plugin

### ISSUE THREAD

**Issue by adriankamena** [fedealvz/Woo-iFactura#1]
Hola! Intento instalar el plugin en WP y me da error.
"No se ha podido descomprimir el paquete. No se encontraron plugins"
Por qué podrá ser?
Gracias.

**Comment by gonzad26** [comment]
Yo lo pude instalar bajando el repositorio (el archivo ZIP) y copiando la carpeta woo-ifactura (la que esta dentro del ZIP) a wp-content/plugins dentro de mi Wordpress.
Una vez que hice eso apareció en la sección de Plugins de mi Wordpress.

Saludos!

**Comment by mdqmatias** [comment]
Hola @fedealvz yo lo tengo instalado, todo configurado tanto los datos de acceso del plugin como todo el tema de afip en ifactura. Me aparece el logito de la factura al lado del pedido "procesando", lo apreto y aparece un relojito. Y no pasa nada mas, voy a ifactura.com.ar y no veo dicho pedido ahi. Algo mas que me falte hacer? Y otra consulta, si o si tiene que ser durante el estado "procesando"? No puede ser durante otro estado? Completado, etc etc Gracias

**Comment by gonzad26** [comment]
Hola @mdqmatias fíjate si te tira algún mensaje de error arriba de los datos de la orden. Quizas le falten datos a la orden.

Saludos!

**Comment by mdqmatias** [comment]
Si @gonzad26 era eso, el faltante de datos. Tengo otro tema, los campos en el checkout no me gustan en ingles y ademas el "tipo de persona" lo tiene que pedir si o si para facturar??? Otros sitios jamas me pidieron eso, por ahi alguien no tiene idea que es eso y no te compra por tener ese dato ahi en el checkout. Es posible que solo se de a elegir consumidor final u otra opcion y que si ponen ponele responsable inscripto ahi aparezca los datos necesarios. Para responsable inscripto jamas en la vida me pidieron si soy persona fisica o juridica, me parece rarisimo...

**Comment by gonzad26** [comment]
Lo de los campos en inglés no llegue a ver ninguno al momento de la compra. Donde los estarías viendo?

Lo que respecta a modificaciones del plugin te sugeriría de dejarlas dichas acá cómo sugerencias de función o que hagas un fork y modifiques el plugin a gusto.

**Comment by mdqmatias** [comment]
Si estoy modificando el plugin yo en cuanto a traducciones, lo que te digo del campo del checkout es esto fijte el adjunto
![image](https://user-images.githubusercontent.com/49917869/64465836-1af71780-d0e5-11e9-80d3-a01d1b943279.png)

**Comment by mdqmatias** [comment]
Al menos el de tipo de persona me gustaria que no estuviera ahi, y de paso pregunto es posible que afip tome la factura sin conocer ese dato? Porque es un dato que confunde.

**Comment by gonzad26** [comment]
Como usuario de iFactura es un dato que el sistema me ha pedido cuando he cargado clientes.

**Comment by mdqmatias** [comment]
Claro, pero creo que no es necesario para facturar. Yo nunca he visto que cuando compro algo me pregunten al momento de hacerme la factura (asi haya pedido A o B) que tipo de persona soy si juridica o fisica. Por eso me gustaria poder quitar esa opcion, insisto, ya noto que es un campo que puede demorar una venta. El 90% de las personas que compran online son consumidor final (y hasta muchos no tienen idea que es ser consumidor final), pero a lo sumo poder configurar en admin esos campos. Por ejemplo solo dejar la opcion consumidor final ya fija y dejar implicito persona fisica (que es el mismo 90%)...

**Comment by mdqmatias** [comment]
Consulto algo mas, al tildar lo de "auto envio" en la config del plugin, significa que al presionar el boton y que el comprobante se haya emitido le llega al cliente automaticamente a su email?

**Comment by fedealvz** [comment]
Hola @mdqmatias 

> Al menos el de tipo de persona me gustaria que no estuviera ahi, y de paso pregunto es posible que afip tome la factura sin conocer ese dato? Porque es un dato que confunde.

Es buena idea! Te propongo que abras un nuevo Issue con esta feature, así no se mezcla todo en una misma conversación y es más legible para trabajarlo a posterior ;-)

> Consulto algo mas, al tildar lo de "auto envio" en la config del plugin, significa que al presionar el boton y que el comprobante se haya emitido le llega al cliente automaticamente a su email?

Exactamente!

**Comment by raeelizalde** [comment]
Hola, con respecto a lo de las traducciones y el tema de los campos de persona y categoría de iva yo los edite en forma directa para que salgan en español y les predefiní los valores más habituales que son consumidor final y persona física, el archivo que edite esta dentro de la carpeta admin del plugin, se los dejo linkeado por si les sirve
https://drive.google.com/file/d/1HoiJTm8Cw7OBtPmhzH7E2POtLzZo8J1x/view?usp=sharing
