### ISSUE TITLE
"La condición impositiva es incorrecta" tengo en checkout con iFactura

### ISSUE THREAD

**Issue by martinrios95** [fedealvz/Woo-iFactura#10]
¡Buenos dias! Soy Martín Ríos.

En un sitio de e-commerce que usa WooCommerce, al realizar el checkout, surge el siguiente problema: el checkout me indica _"La condición impositiva es incorrecta"_, aún **cuando elijo** la parte de condición impositiva y el CUIL/CUIT/DNI...

Estoy usando WooCommerce 3.9 con WordPress 5.2.4.

En **ningún tipo** de _payment gateway_ ni _shipping type_ (contra-entrega, envío por cadete, retiro en sucursal) funciona.

Está configurada la deducción del IVA en la sección **Impuesto** de WooCommerce, que, para este rubro (perfumería), siempre es el 21% de impuesto.

Pruebo desactivar el plug-in de iFactura y funciona normalmente.

Como sugerencia, preferiría que se pudiera editar la Condición Impositiva en la parte de **Pedidos** de la Administración de WooCommerce.
Muy rara vez en un sitio de _e-commerce_, generalmente en el B2C, piden Condición Impositiva, inclusive, muchos **no tienen conocimiento** de ese campo (y mucho menos su significado).

Esperando una pronta respuesta, muchas gracias,

¡Saludos!

**Comment by gonzad26** [comment]
Me ha pasado con ventas anteriores a instalar el plugin que le falta el campo "condicionimpositiva" en la orden.

![image](https://user-images.githubusercontent.com/5983034/80014144-437e2700-84a6-11ea-861f-b74a6f10117d.png)

Si es el caso lo podes agregar a mano y poner el id de condición impositiva. 
Siendo 4 para "Consumidor Final". 1 para Responsable Inscripto, 2 para Exento y 3 para Monotributista.

La condición impositiva es por defecto "Consumidor Final" al momento de la compra, que es el general de los clientes. Para los métodos de pago no es un dato que les interese pero si para iFactura para saber el tipo de comprobante a generar.

![image](https://user-images.githubusercontent.com/5983034/80014474-bbe4e800-84a6-11ea-9c54-c93a52932074.png)

En el caso de que lo quieras ocultar, quizás puedas modificar la clase que muestra los campos en el register.

**Comment by martinrios95** [comment]
No tengo **ningún error** en la administración de WooCommerce ni en los pedidos.

El tema del checkout es que cuando un cliente hace el pedido, salta el error _"La condición impositiva es incorrecta"_, impidiéndolo de continuar, sea cual fuera la Condición Impositiva elegida (o la que está por defecto).

El tema de ocultar la Condición Impositiva se puede realizar de las maneras que en WordPress ya se conocen, pero mi sugerencia es ocultarla por defecto como un _feature_.

¡Saludos!

**Comment by gonzad26** [comment]
Que otros plugins tenes instalados? Te sugiero que revises los nombres de los campos a ver si entra en conflicto con otros plugins que tengas instalados. Porque si aparece eso es que no esta validando correctamente la condición impositiva.

En las siguientes lineas se ve el nombre del campo y su validación: 
* https://github.com/fedealvz/Woo-iFactura/blob/7019b7aa16ea0b0c28367a5533397568e9819062/woo-ifactura/admin/class-woo-ifactura-admin.php#L190
* https://github.com/fedealvz/Woo-iFactura/blob/7019b7aa16ea0b0c28367a5533397568e9819062/woo-ifactura/admin/class-woo-ifactura-admin.php#L323

Yo actualmente lo tengo andando correctamente en Woocomerce 4.0.1 y Wordpress 5.4.

**Comment by martinrios95** [comment]
Aca muestro una captura del suceso:

![image](https://user-images.githubusercontent.com/28807563/80617013-f2c37c80-8a17-11ea-8e53-10ff2d62ace8.png)

**Comment by gonzad26** [comment]
Pudiste revisar eso que te dije de los nombres de los campos a ver si entra en conflicto con algún otro campo que tengas o sea algún campo de otro plugin?

Que plugins tenes instalados que puedan interferir en esa vista?

**Comment by martinrios95** [comment]
Lo único que interviene en esa vista es un plug-in que maneja el front-end de ese checkout.
Ese campo se añadió automáticamente al activar el plug-in de iFactura.

Lo único alterado mediante _hooks_ fue el precio para que no coloque el "_(incluye tanto de impuestos)_".

**Comment by martinrios95** [comment]
Recién revisé el código, y funciona con un problema:
Ustedes verifican la Condición Impositiva con números. En los campos de checkout aparece la cadena de caracteres completa con el nombre en lugar del valor:

![image](https://user-images.githubusercontent.com/28807563/80620326-39b37100-8a1c-11ea-9d86-9e178a3debb7.png)

**Comment by martinrios95** [comment]
Justamente estamos revisando eso.
Mantengo activo el _issue_ hasta descartar un problema de intervención con el plug-in de iFactura.

Estamos revisando el _theme_ y otros plug-ins a ver si no hay otro campo que haga el susodicho problema.

**Comment by fedealvz** [comment]
cierro issue por inactividad.
