### ISSUE TITLE
Problema en el email de compra e inicio de sesión

### ISSUE THREAD

**Issue by gustavonardi** [fedealvz/Woo-iFactura#11]
Hola a todos! Empecé este mes con el servicio de iFactura, se ve muy bueno todo! Ya está todo configurado pero ahora en los emails que recibo cuando alguien realiza una compra me aparece este error de iFactura:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Woo_iFactura_Admin' does not have a method 'woo_ifactura_display_tipopersona_in_email_fields' in /home/desnudandoelmkt/cursos.desnudandoelmarketing.com/wp-includes/class-wp-hook.php on line 289

Además de eso, al momento de querer hacer una factura me tira el error de "inicio de sesión incorrecto" (y en realidad los datos de inicio de sesión ya están cargados).

¿Cómo lo puedo solucionar? El theme es Divi 4.4.2, la versión de WooCommerce es la 4.0.1 y la versión de Wordpress es 5.4.1). Gracias y saludos!!

**Comment by gonzad26** [comment]
Hola! 
Como debería hacer para replicar ese problema? Igual al ser un warning se va quitando el display_errors o el WP_DEBUG del config de Wordpress si eso complica el funcionamiento. Quizás sea algún asunto de compatibilidad con el theme del carrito que tenes. 
Mi sugerencia seria que desactives los errores de PHP y el debug de Wordpress y te fijes si los valores llegan a la Orden en Woocommerce.

<img width="1158" alt="Screen Shot 2020-05-08 at 18 26 32" src="https://user-images.githubusercontent.com/5983034/81450802-7dfbeb00-9159-11ea-8e72-b38606cca21a.png">
<img width="1190" alt="Screen Shot 2020-05-08 at 18 26 38" src="https://user-images.githubusercontent.com/5983034/81450806-80f6db80-9159-11ea-8015-8f525e5afeca.png">

Actualmente lo tengo andando con la versión 4.0.1 y no detecte dicho problema.

Por lo del login fíjate en la configuración del módulo que tiene un modo de pruebas que en realidad va a una instancia de pruebas de iFactura que tiene otro login diferente del contratado y ese se pide a iFactura. Sin ese check podes utilizar el login contratado.

<img width="854" alt="Screen Shot 2020-05-08 at 18 22 48" src="https://user-images.githubusercontent.com/5983034/81450559-0f1e9200-9159-11ea-9fe1-306d4031ba7d.png">

Saludos!

**Comment by gustavonardi** [comment]
Hola Gonza! Gracias por la rápida respuesta! El texto en el mail no me preocupa, el problema real es que al apretar el icono de iFactura me tira un error y no puedo facturar el pedido. El error dice "inicio de sesión invalido". Acá está el texto:

![Captura de pantalla 2020-05-08 a la(s) 18 34 42](https://user-images.githubusercontent.com/65045710/81451476-f7e0a400-915a-11ea-9a4a-e6f52d18cea8.png)

Lo del texto en el email lo puse por si era un dato importante. Los campos personailzados del pedido parecen estar bien:

![Captura de pantalla 2020-05-08 a la(s) 18 39 48](https://user-images.githubusercontent.com/65045710/81451673-5e65c200-915b-11ea-915c-d600034229ca.png)

![Captura de pantalla 2020-05-08 a la(s) 18 40 29](https://user-images.githubusercontent.com/65045710/81451737-805f4480-915b-11ea-844c-58821a8e6c91.png)

Sino voy a intentar actualizar woocommerce y el theme a ver si eso tiene que algo que ver.

**Comment by gonzad26** [comment]
Estas seguro que tenes destildado eso del entorno de pruebas? En el caso que sí, proba conectarte directamente a iFactura desde su web a ver si las credenciales que tenes son correctas.

**Comment by gustavonardi** [comment]
Ahí restablecí mi contraseña de iFactura y parece que ahora se puede! Solo tengo inconvenientes con los campos del checkout que desactivé (como telefono o código postal que no se usan en mi rubro), pero ahora los vuelvo a activar porque supongo que son necesarios para facturar.

Muchas gracias por las respuestas!

**Comment by gonzad26** [comment]
No hay problema!
Si, para facturar tenes un par de datos que son molestos pero necesarios para la factura.

Saludos!
