### ISSUE TITLE
Problemas con la provincia al momento de facturar

### ISSUE THREAD

**Issue by germanrandazzo** [fedealvz/Woo-iFactura#12]
Buenas tardes,

Estoy teniendo problemas a la hora de facturar en woocommerce. Algunos clientes no completan el casillero de provincia y este por defecto esta seteado en CABA y se terminan generando algunas facturas mal ya que la percepción de algunos impuestos no es igual en todas las provincias (ej: ingresos brutos).

Mi consulta es si el plugin lee solamente el campo de provincia o si coteja este dato con el código postal o el CUIT/DNI para ver si corresponde. Quisiera saber si ifactura es el que esta colocando siempre a CABA por defecto Y/o si se podría programar para que tome ese dato a partir del código postal.

Espero haber sido claro para que se entienda el problema. Quedo a la espera de comentarios. Muchas gracias por todo. Saludos.

**Comment by gonzad26** [comment]
Hola German,
Por lo que vi en el código del plugin, si tu cliente no completa la provincia y deja por defecto, es CABA. No importa el código postal que le ponga.

iFactura tiene un padrón de contribuyentes integrado, si tu cliente tiene CUIT, lo puede llegar a rectificar. En el caso de que sea DNI no hay forma de validarlo.

Para activar el padrón: https://help.wnpower.com/hc/es/articles/360019240691-C%C3%B3mo-habilitar-el-Padr%C3%B3n-A5-en-iFactura
Pero ojo que solo sirve si son clientes con CUIT y la condición impositiva no es Consumidor Final.

**Comment by germanrandazzo** [comment]
Genial Gonzalo, muchas gracias.

Estamos viendo también por otro lado que es el mismo woocommerce el que nos cambia la provincia a CABA por default cuando cambiamos el estado de un pedido. Tenemos que revisar por varios lados de donde proviene el problema. Muychas gracias por todo. Saludos.
