### ISSUE TITLE
Tamaño de la fuente en las facturas

### ISSUE THREAD

**Issue by germanrandazzo** [fedealvz/Woo-iFactura#13]
Buenos días,

Vuelvo a molestarlos con una duda. estamos generando facturas con mucho detalle y hemos notado que los campos de Precio unitario / bonificación / subtotal están teniendo poco espacio para que entre el contenido en la tabla por lo que genera una doble línea y eso da como resultado facturas muy largas. Adjunto captura

Te nemos manera de agradar el ancho de esas columnas o reducir el tamaño de las fuentes para así achicar el alto de las filas? Ya que se nos estan generando facturas de varias hojas. Aguardo respuesta. Desde ya muchas gracias por su atención.

Saludos, Germán.

![FACTURAS MÁS CHICAS](https://user-images.githubusercontent.com/60151893/84047425-a148ce80-a981-11ea-9870-07bedadb6c48.jpeg)

**Comment by gonzad26** [comment]
Eso ya es cuestión de iFactura, no del plugin. En iFactura, igualmente, no vi ninguna opción para ello.

**Comment by germanrandazzo** [comment]
Pensé que quizás podíamos tocar algo en el CSS del plugin, no tengo idia. Se los traslado a ellos entonces. Muchas gracias por la pronta respuesta igualmente. Saludos.
