### ISSUE TITLE
Problema con el lenguaje mostrado

### ISSUE THREAD

**Issue by MaritoCe** [fedealvz/Woo-iFactura#15]
Hola! No se por qué hay algunas etiquetas de la página "Finalizar compra" que me aparecen en inglés. Revisé los archivos .PO tanto de español de España como de Argentina y en ambos figura traducido.

Cuál puede ser el problema?
Mi web es chinarodriguez.com

Muchas gracias.

**Comment by gonzad26** [comment]
Hola!
No encontré ninguna referencia en el código del plugin que haga uso de un string para un "Finalizar compra". Te diria que te fijes en otros plugins o themes que puedan modificar la sección que decis.

**Comment by MaritoCe** [comment]
Hola Gonza!

No, las etiquetas que no está traduciendo son las que se encuentran dentro de la página "Finalizar compra" de Woocommerce. Las etiquetas puntuales son:

Tax Treatment
People Registry Type

Gracias!

**Comment by fedealvz** [comment]
Hola @MaritoCe 
¿qué idioma tenés configurado en WordPress y en WooCommerce? (exactamente)

**Comment by MaritoCe** [comment]
Hola!

Español (es_ES)

**Comment by gonzad26** [comment]
Lo tengo en el mismo lenguaje y el checkout lo veo correctamente. 
![image](https://user-images.githubusercontent.com/5983034/87357643-bb566d80-c53a-11ea-81f7-e09084988c9c.png)

![image](https://user-images.githubusercontent.com/5983034/87357574-99f58180-c53a-11ea-93df-f212bcd4b5b2.png)
No tendrás algún plugin que altere el html del checkout o agregue cosas en caliente?

**Comment by fedealvz** [comment]
Cierro issue por falta de respuesta.
