### ISSUE TITLE
Problema con woocommerce

### ISSUE THREAD

**Issue by luisway2net** [fedealvz/Woo-iFactura#16]
Hola, estoy probando el servicio en wordpress con woocommerce y estoy teniendo el siguiente problema:

Notice: Undefined index: billing_dni_ifactura in /wp-content/plugins/woo-ifactura/admin/class-woo-ifactura-admin.php on line 286

Notice: Undefined index: billing_condicionimpositiva_ifactura in /wp-content/plugins/woo-ifactura/admin/class-woo-ifactura-admin.php on line 287

No se si falta configurar algo o que esta mal. Descargue le plugin de github y segui los pasos que indica.

Gracias

**Comment by gonzad26** [comment]
Hola! Haciendo que cosa ves esos Notice? Al ser notice no debe ser graves. Seguro sea accediendo a datos de clientes que no existe porque no tenias el módulo anteriomente. 
También desactivar el debug de Wordpress y el display_errors de PHP para quitar los notice seria recomendado para el entorno final.
En esta sección trata el tema: https://github.com/fedealvz/Woo-iFactura#ventas-previas-a-la-instalaci%C3%B3n-del-plugin

**Comment by luisway2net** [comment]
Esto sucede cuando estoy en la pagina del carrito, y selecciono finalizar compra para pasar al checkout. 
Esos dos mensajes los imprime sobre el formulario de registro del comprador, antes de completar algun campo.

**Comment by gonzad26** [comment]
Te diria que saques el debug de Wordpress y pruebes a ver si funciona el plugin correctamente.

**Comment by luisway2net** [comment]
Hola, si como dijiste, saque el debug y desapareció.

**Comment by luisway2net** [comment]
Ahora veo el botoncito de ifactura en pedido. Pero cuando lo presiono dice esto: Inicio de sesión incorrecto.
No se si tendra que ver con que estoy usando el modo de prueba o que todavía no se termino la activación de la cuenta.
O no se que otra cosa puede ser.

**Comment by gonzad26** [comment]
Para usarlo en producción necesitas contratar un plan y ahí te dan una cuenta. 
Para el entorno de pruebas tenes que solicitar la demo del sistema, te van a dar una cuenta para pruebas.
El error es porque tenes mal el login.

**Comment by luisway2net** [comment]
estoy usando el mismo user y pass con que me logueo al panel de ifactura

**Comment by gonzad26** [comment]
Si estas usando el login que contrataste, es solo para el entorno de producción.
Para el entorno de pruebas, es otro login que tenes que pedir.

Fijate si tenes activado el modo de pruebas en la configuración del plugin.
![image](https://user-images.githubusercontent.com/5983034/87569277-42235b80-c69d-11ea-8243-554897de7ef3.png)

**Comment by fedealvz** [comment]
Cierro issue por falta de respuesta.
