### ISSUE TITLE
Problemas para emitir comprobantes

### ISSUE THREAD

**Issue by Matiasi** [fedealvz/Woo-iFactura#17]
Hola cómo están? Esta semana hice el cambio a Responsable Inscripto y estoy probando iFactura. Intentando emitir comprobantes tengo dos errores:

Me indica "The Provincia field is required" a pesar de que la provincia está especificada (es un dato obligatorio en la tienda). Esto pasa en pedidos realizados antes y después de instalar el plugin.

Otro inconveniente que tengo es que me indica: No se puede calcular el descuento global sobre los productos dado que el descuento no esta aplicado sobre los impuestos tambien. Por ende no se puede calcular el IVA verdadero.936

Tengo un plugin que aplica un 10% de descuento a los que abonan por transferencia (lo que hace es crear una fee o cuota con un valor negativo). Qué podría hacer? Tengo muchos comprobantes por emitir aun que tienen este descuento aplicado.

Muchísimas gracias

**Comment by gonzad26** [comment]
1) Tendrías que revisar si la provincia se esta cargando correctamente en el perfil del comprador como para que se envié correctamente la información a iFactura. También el nombre de la provincia si esta bien escrito como en el código del plugin como para que lo identifique.
2) El plugin de descuentos que estas usando esta agregando un producto de valor negativo como descuento y de esta forma no resta de igual manera sobre los impuestos.  No es la mejor práctica esa forma de aplicar descuentos. Por eso te tira ese error y no puede calcular el valor de impuestos (en este caso IVA) de manera correcta. La solución seria que busques un plugin que haga un descuento sobre los productos o si lo hace de forma global también lo haga sobre los impuestos.

**Comment by Matiasi** [comment]
1. La provincia aparece cargada, lo único que se me ocurre es que le cambié el nombre usando Locotranslate (por default creo que es Ciudad Autónoma de Buenos Aires y yo lo cambié a Capital Federal) Podría ser eso?

2. Eliminando el fee negativo y aplicando un cupón común del 10% deja de aparecer el error. Voy a buscar otro plugin.

Gracias!

**Comment by gonzad26** [comment]
1) Si el nombre de la provincia te esta complicando ahi. Busca "Ciudad Autónoma de Buenos Aires!" por código: https://github.com/fedealvz/Woo-iFactura/blob/7377d39b678b1c726cd3ccf8948905708e61c217/woo-ifactura/admin/class-woo-ifactura-admin.php#L1060

2) Buenísimo que lo hayas solucionado. El cupón de descuento que funciona lo aplicaste con algún plugin o algo?

**Comment by Matiasi** [comment]
1. Genial, resuelto! 
2. Lo hice manualmente desde la order edit screen. Creo que voy a tener que hacer eso con todos los pedidos que me quedaron así. 

Te hago una consulta @gonzad26 , no soy programador, vos estás vinculado con el mantenimiento de este plugin? Veo que no hay forma de enviar mensaje privado por GitHub. Necesitaría hacer unas pequeñas modificaciones que entiendo van más allá del soporte del plugin y quizás vos me puedas cotizar el trabajo. Pido disculpas si no se puede pedir este tipo de servicios en la plataforma.

Básicamente ecesitaría que en caso de estar vacíos ciertos campos el plugin los "autocomplete" a la hora de emitir un comprobante: Condición Impositiva (Consumidor final), Tipo de Persona (Física) y DNI (11111111).  Gracias!

**Comment by Matiasi** [comment]
Los comprobantes se están emitiendo con un IVA del 0%. Cómo tendría que ser la configuración en Woo para que sean con 21% pero sin modificar los precios que se muestran al público (que sean con el IVA incluido y sin el detalle del IVA, tal como se hace en Argentina) Mil gracias!

**Comment by gonzad26** [comment]
Para lo anterior. El problema de la solución que plateas es que si el comprobante es mayor a 5000 esos datos son incorrectos y no te va a dejar facturar. Hay un mandamiento de AFIP que restringe eso.

Por lo otro, hay un issue de otro usuario con un problema parecido y configurandolo así quedo OK. Yo lo tengo andando así.
Issue https://github.com/fedealvz/Woo-iFactura/issues/7

**Comment by Matiasi** [comment]
Muchas gracias por tu respuesta. Voy a buscar una solución alternativa.

En el caso del ejemplo de la Issue #7 es un mayorista por lo que quiere excluir el IVA . Mi tienda es a consumidor final, por lo que el IVA no tiene que estar discriminado ni visualizarse en la web, tiene que ser el precio completo. En la factura B tampoco tiene que aparecer (y no aparece). El problema es que en el libro de IVA ventas que descargo de iFactura y chequeando los comprobantes que llegan a la AFIP aparecen con IVA 0%, como se puede ver en esta captura

![Comprobantes](https://user-images.githubusercontent.com/21226365/88316871-d3727d80-ccee-11ea-9626-74b7751a5f7d.jpg)

**Comment by gonzad26** [comment]
Al ser factura B, por lo que decís, tenes que discriminar el IVA para vos y tus liquidaciones (IVA crédito fiscal). Por eso tenes que configurar los impuestos en Woocommerce para informarle correctamente a iFactura que queres facturar.

iFactura en facturas B NO le va a discriminar el IVA al cliente (sea consumidor final o un cliente puntual). En factura A si se los va a discriminar.

**Comment by Matiasi** [comment]
Claro, es un tema de la configuración de Woo pero no sé cómo configurarlo. Con la configuración actual no se ve en ningún lado el IVA discriminado, la factura B se emite correctamente pero no se discrimina el IVA para mis liquidaciones (es como si cobrar IVA 0%).

<img width="592" alt="Screen Shot 2020-07-23 at 14 19 58" src="https://user-images.githubusercontent.com/21226365/88317399-9955ab80-ccef-11ea-8b63-6c0976933993.png">

Si yo a esa configuración le especifico un valor de IVA 21% usando tarifa estándar como hago acá

![image](https://user-images.githubusercontent.com/21226365/88420797-d2f4e800-cdbd-11ea-977e-06563f8e9684.png)

Woo calcula los impuestos de forma errónea. No le encuentro la lógica al valor que tira, pensé en alguna superposición de impuestos pero el único impuesto ingresado es del 21%. Desactivé todos los plugins, cambié el theme, todo y aún así lo calcula mal. 

<img width="567" alt="Screen Shot 2020-07-24 at 14 56 32" src="https://user-images.githubusercontent.com/21226365/88420830-df794080-cdbd-11ea-93cf-6b65d50b6669.png">

Realmente no sé como sería la configuración correcta para este caso.

**Comment by gonzad26** [comment]
Hola!
Al igual que el usuario del #7  lo tengo configurado así y me funciona correctamente. Fíjate si te sirve de guía.
![image](https://user-images.githubusercontent.com/5983034/88440124-6c82c080-cde3-11ea-9b26-26b903b31f44.png)

![image](https://user-images.githubusercontent.com/5983034/88440157-89b78f00-cde3-11ea-826a-645dbf445324.png)

![image](https://user-images.githubusercontent.com/5983034/88440216-b23f8900-cde3-11ea-96a6-71c99b1aa1be.png)

Algo importante tambien, es que los cambios que hagas en esta secciones se van a ver reflejados en nuevas ordenes de venta. No en las previas al cambio como en este ejemplo:
![image](https://user-images.githubusercontent.com/5983034/88440255-d602cf00-cde3-11ea-9b8b-bbf17f8a9e86.png)

**Comment by Matiasi** [comment]
Si, hice pruebas con esa configuración y anduvo. Entonces el plugin no soporta la configuración "Si, voy a introducir los precios con impuestos incluidos". El problema es que tengo todos los precios con impuestos incluidos y muchas ventas por facturar con esos valores y sin desglosar impuestos. Además preferiría, por cuestiones de funcionamiento del negocio, seguir introduciendo los precios con impuestos incluidos. Es posible modificar el plugin para que automáticamente informe a iFactura/AFIP que la alicuota es IVA 21%? En mi caso va a ser la misma alicuota para todos los productos y el envío. Si conocés algún programador para recomendarme que pueda hacer este trabajo te lo agradecería. Yo no tengo los conocimientos técnicos necesarios. Saludos y buen finde!

**Comment by fedealvz** [comment]
Hola @Matiasi podés buscar programadores en la [Comunidad de WNPower - Partners & Freelancers - Programación Web](https://help.wnpower.com/hc/es/community/topics/360001624752) o publicar tu proyecto en la [Bolsa de Trabajo](https://help.wnpower.com/hc/es/community/topics/360001624812)
