### ISSUE TITLE
No puedo subir el plugin

### ISSUE THREAD

**Issue by holacomunicacion** [fedealvz/Woo-iFactura#18]
Hola! Como estan? Al momento de subir el ZIP a Wordpress este no se descomprime, 

Descomprimiendo…

Instalando el plugin…

No se ha podido descomprimir el paquete. No se encontraron plugins.

La instalación del plugin ha fallado.

Volver al instalador de plugins

Que puede estar pasando? gracias!

**Comment by gonzad26** [comment]
Hola!

Proba realizar la instalación como describe el readme del repositorio. https://github.com/fedealvz/Woo-iFactura#instalaci%C3%B3n

Si te bajaste el zip desde el descargar de Github no te va a encontrar el plugin porque los archivos del plugin estan dentro de una carpeta y tienen que ir sueltos dentro del zip para que te reconozca el plugin.

Saludos!
