### ISSUE TITLE
Problemas al aplicar descuentos por metodos de pago

### ISSUE THREAD

**Issue by luisway2net** [fedealvz/Woo-iFactura#19]
Hola estoy usando plugins para aplicar un descuento por método de pago (y funcionan), pero al usar el plugin ifactura con ninguno logro que se pueda facturar. Con todos obtengo el siguiente error:

"No se puede calcular el descuento global sobre los productos dado que el descuento no esta aplicado sobre los impuestos tambien. Por ende no se puede calcular el IVA verdadero."

Los plugins que probe son:
Payment Gateway Based Fees and Discounts for WooCommerce
Woo Payment Discounts
Booster for WooCommerce

Con este otro plugin funciona pero genera un cupon para hacerlo y confunde al cliente, por eso no me sirve
Discounts Per Payment Method on WooCommerce

Hay alguna solución a esto?

**Comment by gonzad26** [comment]
Hola! se ve que es plugins de descuento que probaste no aplican el descuento sobre los impuestos por eso te tira ese error. 
Te recomendaría que trabajes con los plugins que funcionan para aprovechar la automatización que te trae el plugin. Sino podes intentar modificar el plugin para lograr alguna funcionalidad o mejora.

Saludos!
