### ISSUE TITLE
Condición Impositiva

### ISSUE THREAD

**Issue by adriankamena** [fedealvz/Woo-iFactura#2]
Hola, me pide la condición impositiva pero no sé en donde puedo cambiarla o agregar alguna.
Agradecería su asistencia.
Gracias!

**Comment by gonzad26** [comment]
Si te referís a tu condición impositiva, la podes cambiar desde Ajustes en la sección de WooCommerce, solapa de Configuración de iFactura.

<img width="1740" alt="Screen Shot 2019-08-24 at 09 44 41" src="https://user-images.githubusercontent.com/5983034/63637578-0bdb8880-c654-11e9-9eac-d6a80755737d.png">

Donde dice Responsable Inscripto, podes elegir entre Monotributo, Responsable Inscripto y Exento.

**Comment by adriankamena** [comment]
No, me refiero a los campos del cliente. Documento, Condición, Tipo de Persona. No puedo editarlos desde "Pedidos". 
![InkedCaptura 11_LI](https://user-images.githubusercontent.com/54455744/63638878-fc643b80-c663-11e9-95aa-c65556523f40.jpg)

**Comment by gonzad26** [comment]
Si note lo mismo cuando ya tenés ordenes previamente cargadas con clientes que no completaron esos datos por todavía no tener el plugin instalado.

Lo que hice fue ir a la sección de campos personalizados y ahi podes ir agregando esos valores a mano.

<img width="1668" alt="Screen Shot 2019-08-24 at 11 49 19" src="https://user-images.githubusercontent.com/5983034/63639025-6e895000-c665-11e9-8aa6-aee69326e1ca.png">

Complete con lo siguiente: 
*tipopersona: 1 (Física) 2 (Jurídica)
*dni: Dni del cliente o valor en 1 sino lo tengo y lo puedo facturar como consumidor final
*condicionimpositiva: 4 para "Consumidor Final". 1 para Responsable Inscripto, 2 para Exento y 3 para Monotributista.

Los valores de tipo de persona y condición impositiva lo encontré probando números, actualizando el campo y refrescando la página.

Después vas a ver que cuando un cliente nuevo te compre, va a tener que completar esos datos y te van a llegar a las ordenes con dichos datos ya completados. Con eso que hace el cliente ya no tenés que hacer más que emitir el comprobante y listo!

Espero que te sirva el tip!

**Comment by adriankamena** [comment]
Excelente! Lo voy a probar. Gracias!

**Comment by gonzad26** [comment]
Es un poco molesta la transición a hacer las facturas, más cuando uno no tiene los datos del cliente. Pero una vez que te haces ese trabajito, te olvidas!

**Comment by adriankamena** [comment]
Pero los clientes que ya están registrados, cada vez que compren voy a tener que hacer esto? O hay manera de actualizar estos campos en el usuario para que ya queden?

**Comment by gonzad26** [comment]
Se supone que ya les quedan cargados los campos ahora porque previamente no estaban.

**Comment by adriankamena** [comment]
Ah ok! Gracias.

**Comment by adriankamena** [comment]
Te vuelvo a molestar. No me aparecen las opciones en "Añadir un campo personalizado"

**Comment by gonzad26** [comment]
No ves la sección de "Campos Personalizados" debajo de donde esta el botón "Recalcular" donde, tambien, están los totales?

Los campos personalizados es una característica de WooCommerce debería estar ahi debajo.

**Comment by adriankamena** [comment]
Listo, ya lo pude hacer. No sabía como funcionaba. Me tira otro error ahora.
![InkedCaptura 12_LI](https://user-images.githubusercontent.com/54455744/63639985-16f0e180-c671-11e9-8391-5799baca0ef2.jpg)

Si se refiere al campo DNI, ya lo ingresé con valor 1. También probé ingresando un número de dni cualquiera pero tampoco funciona.

**Comment by gonzad26** [comment]
Probaste mandando un valor tipo 9999999 que seria un DNI válido? Acabo de hacer una prueba y lo pude emitir correctamente. Te paso captura de como esta hecho el pedido.

![1](https://user-images.githubusercontent.com/5983034/63640168-7bad3b80-c673-11e9-99a6-8f3e0125a4a7.PNG)
![2](https://user-images.githubusercontent.com/5983034/63640169-7bad3b80-c673-11e9-9b41-ce598f089a6c.PNG)

**Comment by adriankamena** [comment]
Sí! esa fue de hecho la última prueba y sigue igual. Te mando captura. Será por los campos que ya tiene del pedido cerrado?
![Captura 13](https://user-images.githubusercontent.com/54455744/63640268-77355280-c674-11e9-9058-8bdc19d982a9.jpg)

**Comment by gonzad26** [comment]
Proba escribiendo el campo "dni" como "DNI" en mayusculas. Quizas no encuentra el campo. Es lo primero que veo diferente de mi prueba y la tuya.

**Comment by adriankamena** [comment]
Sí funcionó. Había probado en mayúsculas pero poniendo 1 en el valor. Pero con 99999999 funcionó.
Gracias!

**Comment by gonzad26** [comment]
Bárbaro! De nada! 

Ojala te resulte tan útil como a mi.

Saludos!

**Comment by adriankamena** [comment]
Hola! Me sale el siguientes error:
Error en WSFE: La suma de los campos Importe en IVA debe ser igual al valor ingresado en ImpIVA.
Por lo que estuve viendo tiene que ver con el redondeo al discriminar el IVA. 
También me sale el error "Valor unitario inválido". 
Tenés idea que podrá ser?
Gracias!

**Comment by gonzad26** [comment]
Ahí me mataste. no me paso. Que valores por ejemplo te da problemas?

**Comment by adriankamena** [comment]
El error en WSFE lo devuelve el servidor de la AFIP, sabés a quien le puedo consultar? 
EL error del valor unitario inválido es rarísimo. No sé a que se refiere. Tiene productos similares a la primer factura que hice y que fue bien.

**Comment by adriankamena** [comment]
Tengo estos errores no sé si tendrá que ver:
En el fichero wp-admin/error_log del WordPress:

[24-Aug-2019 21:21:30 UTC] The WC_Order::get_item_meta function is deprecated since version 3.0. Replace with wc_get_order_item_meta.
[24-Aug-2019 21:21:30 UTC] The WC_Order::get_item_meta function is deprecated since version 3.0. Replace with wc_get_order_item_meta.

**Comment by MaritoCe** [comment]
Gonza, gracias por la data! Viene funcionando, pero ahora me pide el Código postal. Yo lo había sacado de mi checkout porque no lo necesitaba, pero ahora lo volví a activar porque iFactura me lo pide. El tema es que no encuentro el valor del campo para poder agregarlo manualmente, sabés cuál es?

Gracias!

**Comment by gonzad26** [comment]
Me alegro que te haya funcionado, en la columna facturación (la del medio de las 3) donde están los datos del cliente, hay un lápiz para editar los datos. Ahí podes especificar el código postal.

Saludos!

**Comment by MaritoCe** [comment]
Excelente! Y, espero que lo último, cuando intento generar el comprobante me tira error. Y si voy al error.log me dice lo siguiente:

"[03-Dec-2019 16:16:58 UTC] PHP Notice:  Undefined index: _billing_address_1 in /wp-content/plugins/woo-ifactura/admin/class-woo-ifactura-admin.php on line 791
[03-Dec-2019 16:16:58 UTC] PHP Notice:  Undefined index: _billing_address_2 in /wp-content/plugins/woo-ifactura/admin/class-woo-ifactura-admin.php on line 792
[03-Dec-2019 16:16:58 UTC] PHP Notice:  Undefined index: _billing_city in /wp-content/plugins/woo-ifactura/admin/class-woo-ifactura-admin.php on line 793
[03-Dec-2019 16:16:58 UTC] PHP Notice:  Undefined index: _billing_phone in /wp-content/plugins/woo-ifactura/admin/class-woo-ifactura-admin.php on line 794

Sabes a qué se debe? Esos datos están cargados, excepto la dirección 2 y el teléfono. 

Gracias!

**Comment by MaritoCe** [comment]
No, perdón! Justo ese cliente no había completado esos campos y los completé a mano y funcionó. Hay alguna forma de hacer que no sean obligatorios? El teléfono, la dirección dos, etc. No son necesarios para un consumidor final, menos si es menor a $5000 la compra.

**Comment by MaritoCe** [comment]
Y otra cosa que no pude encontrar, es cómo cambiar la fecha del comprobante. Apretas el botón de generar comprobante y te lo hace con la fecha de hoy. No se puede cambiar eso?

**Comment by gonzad26** [comment]
El comprobante se genera el día que se presiona el botón de emitir comprobante.

Efectivamente esos datos son opcionales y los notice que ves son inofensivos porque te dice que justamente los datos no están. Ahora si tenes un mensaje de error de iFactura puntual comentalo.

**Comment by MaritoCe** [comment]
Perfecto gracias!

**Comment by MaritoCe** [comment]
Perdón, yo otra vez por acá. Tengo un problema que es que cuando genera el comprobante lo genera como "tipo: producto" y yo vendo servicios. Es una diferencia importante para AFIP. Eso puedo modificarlo en algún lado?

**Comment by gonzad26** [comment]
Eso lo podés cambiar cuando editas los ítems del comprobante en iFactura.

**Comment by gonzad26** [comment]
Perdón me confundí cuando usas el editor de facturas de iFactura. 
Claro este lo hace de forma automática y no lo podes editar desde Woocomerce.  

Editando el plugin podrías llegar a forzarlo a servicio.

**Comment by MaritoCe** [comment]
Gracias Gonza. Si alguien sabe dónde debería cambiar el código para que me tome el tipo como "servicios" en lugar de "productos" muchas gracias!

Saludoos!

**Comment by MaritoCe** [comment]
Estuve revisando el plugin y encontré lo siguiente. Está el campo "ConceptoFactura" que es lo que estoy necesitando si no me equivoco, donde el valor "1" es para Productos y "2" para servicios. En el archivo class-woo-ifactura-admin.php encontré este ciclo:

`foreach($Bienes as $linea)
        {
            $factura->DetalleFactura[$i]->Cantidad = intval($linea['Cantidad']);
            $factura->DetalleFactura[$i]->ValorUnitario =  floatval($linea['ValorUnitario']);
            $factura->DetalleFactura[$i]->Total =  floatval($linea['Total']);
            $factura->DetalleFactura[$i]->Descripcion =  $linea['Descripcion'];
            $factura->DetalleFactura[$i]->Codigo =  $linea['Codigo'];
            $factura->DetalleFactura[$i]->AlicuotaIVA = $linea['AlicuotaIVA'];
            $factura->DetalleFactura[$i]->UnidadMedida = 7;
            $factura->DetalleFactura[$i]->Bonificacion = $linea['Bonificacion'];
            $factura->DetalleFactura[$i]->IVA = floatval($linea['IVA']);            
            $factura->DetalleFactura[$i]->ConceptoFactura = 1; //PRODUCTOS           
            $totalfinal = $totalfinal + $linea['Total'];
            $iva = $iva + $linea['IVA'];
            $i = $i + 1;
        }`
Si hago el cambio en la línea donde aparece "conceptofactura" ya tendría resuelto mi problema? Ese dato además de aparecer en la factura como "Servicio" le figura a la AFIP con ese concepto?

Mil gracias!
Saludos

**Comment by gonzad26** [comment]
Te diría que si con el número 2 debería ser servicio en lugar de producto. 

https://github.com/wnpower/iFactura-API-Integracion#tablas-de-sistema
