### ISSUE TITLE
Habilitar campos DNI y 

### ISSUE THREAD

**Issue by tiendaupego** [fedealvz/Woo-iFactura#20]
Buenas tardes!

Me podrán decir como puedo habilitar los campos de DNI y Condición impositiva que aplica trae automáticamente el pluging?
Mi idea es poder facturar manualmente pero me falta habilitar estos dos campos para que la factura se genere correctamente..

Ya intente varias cosas y no logro hacerlo!

Gracias de antemano a quien lo pudo solucionar

![image](https://user-images.githubusercontent.com/64430847/91620285-e4ee1b80-e965-11ea-8ed8-620dafda2a58.png)

**Comment by gonzad26** [comment]
Hola!
Lo dice acá https://github.com/fedealvz/Woo-iFactura#ventas-previas-a-la-instalaci%C3%B3n-del-plugin

Agregas esos campos personalizados y listo, vas a ver que se completan esos 2. Por más que la guía dice que son 3 campos personalizados, en realidad completando los 2 que menciona estas.

Saludos!

**Comment by rosariokhouri** [comment]
Hola! Yo no tengo problemas en generar el documento pero no puedo lograr que me tome el campo personalizado de la **condición impositiva**. Hasta ahora edito el pedido y pongo 4 en el campo de la condición pero quisiera saber cómo solucionarlo de forma permanente. 
Saludos

**Comment by gonzad26** [comment]
Hola! Completando dicho campo personalizado levanta la condición impositiva. Podrías subir una captura de los campos personalizados a ver si se me ocurre algo?

Yo lo tengo así:
![image](https://user-images.githubusercontent.com/5983034/94354761-e68a2c80-0054-11eb-8cba-89887bd1cc07.png)
Y los podes poner de la siguiente manera
![image](https://user-images.githubusercontent.com/5983034/94354770-f86bcf80-0054-11eb-9ecb-1a208259d8f7.png)

Saludos!

**Comment by rosariokhouri** [comment]
Este es un pedido de prueba. No me toma la condición impositiva. 
![Captura de pantalla 2020-09-30 a la(s) 14 00 11](https://user-images.githubusercontent.com/61284939/94716477-4d456980-0325-11eb-8117-c877e214e4e8.png)

Esto es luego de generar los campos personalizados. Todos los pedidos han sido generados CON el plugin en uso. Sigo los pasos que me mandás pero tengo que repetir los pasos en cada pedido... no sé qué estoy haciendo mal. No sé si es la idea que cada pedido tenga que llenarse de esa forma...

![Captura de pantalla 2020-09-30 a la(s) 14 01 19](https://user-images.githubusercontent.com/61284939/94716595-75cd6380-0325-11eb-8a8e-0c104dd10b21.png)

**Comment by gonzad26** [comment]
Fijate que tenes el campo 2 veces y ahi te toma el vacio y no puede procesar el valor. Este proceso lo tenes que hacer con ventas previas al uso del plugin.

**Comment by rosariokhouri** [comment]
El plugin está instalado desde que se comenzó a desarrollar el sitio. Todas
las ventas han sido con el plugin. ¿Debería hacer la instalación de vuelta?

**Comment by gonzad26** [comment]
Tendrías que revisarlo porque cuando se instala el plugin te agrega campos en el checkout para que tu cliente complete dichos datos. 
También puede ser que el theme de tu checkout altere dicho comportamiento como este caso que tenia modificaciones que alteraban los campos: https://github.com/fedealvz/Woo-iFactura/issues/10

**Comment by rosariokhouri** [comment]
Sí, era incompatibilidad con un plugin (Custom WooCommerce Checkout Fields
Editor) que modificaba una línea del checkout. Cambié esa modificación -la
agregué con un snippet- y ahora me aparecen valores en el select de la
condición impositiva.
Listo, muchas gracias!

**Comment by gonzad26** [comment]
Bárbaro que te anduvo y gracias por compartir con que plugin hubo conflicto para saberlo a futuro.
