### ISSUE TITLE
Algunos errores

### ISSUE THREAD

**Issue by paulabender** [fedealvz/Woo-iFactura#21]
Nada grave. Quiero reportar dos errores. 
1. El .zip no es instalable desde admin de Wordpress, lo descargué lo descomprimí y lo tuve que subir a mano desde el administrador de archivos del servidor.
2. Cuando estoy en la pantalla de finalizar la compra desde el frontend, es un checkout en pasos, en la primera pantalla donde ingresan datos presonales (incluido DNI), si salgo de esa pantall me aparece un mensaje de alerta vacío.

**Comment by fedealvz** [comment]
Hola @paulabender ¡gracias por el feedback! Te respondo:

1. Las instrucciones de instalación podés encontrarlas acá: https://github.com/fedealvz/Woo-iFactura#instalaci%C3%B3n

2. ¿El checkout en pasos es el estándar de WooCommerce o lo estás haciendo con algún plugin? Podrías enviarme una captura de pantalla y URL de ejemplo para revisarlo?

Saludos!

**Comment by paulabender** [comment]
Hola Federico,

Gracias por tu respuesta. 

Sí, así es como lo instalé, porque intenté subirlo e instalarlo como cualquier plugin, desde el admin de WP, Añadir nuevo, y no funcionó. 

El sitio es www.caju.com.ar, uso un plugin de checkout de múltiples pasos.



Saludos
Paula

**Comment by paulabender** [comment]
Federico, 
Otra cosa más. No es posible editar una orden anterior a la habilitación del plugin en WooCommerce para agregar los datos faltante para facturar. ¿Hay alguna solución?

**Comment by gonzad26** [comment]
Hola! 
Esa info la tenes en el README del proyecto. Acá tenes el link: https://github.com/fedealvz/Woo-iFactura#ventas-previas-a-la-instalaci%C3%B3n-del-plugin

Es agregar 2 campos personalizados a las ordenes de venta que tengas previamente creadas a la instalación del plugin.

Saludos!

**Comment by paulabender** [comment]
Hola Federico, 

Perdón que te moleste nuevamente. Había leído el readme, pero no explica mucho, dice “deberás los 3 campos personalizados”. Y en las opciones de Nombre del campo personalizado no aparece Documento, Condición ni Tipo de persona. ¿Me das una mano con eso?

Gracias

**Comment by gonzad26** [comment]
Los tenes que cargar a mano si no los detecta. 
En realidad son 2 ahora. **DNI** y **condicionimpositiva**
![image](https://user-images.githubusercontent.com/5983034/92410411-5a05e180-f11a-11ea-9d33-f301b76afe47.png)

> *dni: Dni del cliente o valor en 1 sino lo tengo y lo puedo facturar como consumidor final
> *condicionimpositiva: 4 para "Consumidor Final". 1 para Responsable Inscripto, 2 para Exento y 3 para Monotributista.

Más info: https://github.com/fedealvz/Woo-iFactura/issues/2

**Comment by paulabender** [comment]
A mí no me aparecen DNI ni condicionimpositiva en las opciones.

**Comment by gonzad26** [comment]
> Los tenes que cargar a mano si no los detecta.
> En realidad son 2 ahora. **DNI** y **condicionimpositiva**

Si no te aparecen en el dropdown tenes que escribirlos a mano por primera vez. Lo haces presionando en el link Nuevo (el campo se convierte en un campo de texto y podes poner lo que quieras)  o en "Añadir un campo personalizado" (aparece arriba una nueva fila con un campo personalizado para poner el nombre y valor que quieras.

![image](https://user-images.githubusercontent.com/5983034/92412341-ec5db380-f121-11ea-866a-b92d92bcf70b.png)

**Comment by paulabender** [comment]
Pude! Gracias por la paciencia! Ahora estoy viendo que tendré que hacer ese proceso en todas las compras anteriores al plugin…

Ahora tengo un inconveniente, necesito editar los items a facturar previo a confirmar la emisión del comprobante. Me está incluyendo el envío y yo no facturo eso. ¿cómo puedo hacer?

**Comment by gonzad26** [comment]
En dicho caso tendrías que eliminar del detalle de la venta, el costo del envió dado que el módulo envía toda la información que contenga esa orden a iFactura.

**Comment by paulabender** [comment]
Un pedido ya pagado no es editable, y si además está pagado con MercadoPago me puede generar líos con los cobros. Me parece que debería haber una instancia previa a la emisión de la factura donde se puedan editar detalles (como sí se puede hacer para las facturas de MercadoLibre con iFactura), sea en el entorno de WordPress o de iFactura, no es un detalle menor.

**Comment by gonzad26** [comment]
La idea es justamente automatizar lo más posible la facturación desde Woocommerce por eso el plugin estimo que no tiene pasos intermedios adicionales para facturar. Las versión de Mercadolibre, es iFactura el que se conecta a Mercadolibre y acá, es nuestro Wordpress el que se conecta con iFactura.

Igualmente el plugin es open source lo podes modificar y adaptar a tu gustos y necesidades.

**Comment by paulabender** [comment]
En ese caso, no creo que pueda usarlo. Soy diseñadora, no sé programar. 
Quizás el día que se pueda lo reconsideraré, estoy tomando el mes de prueba en iFactura para ver si me sigo con el servicio y estoy viendo detalles, tanto en el plugin para WC como en la facturación para MercadoLibre.

Muchas gracias

**Comment by paulabender** [comment]
Pensaba que quizás se podía mandar a iFactura y ahí poder editar antes de emitir. Quizás no hace falta modificar (tanto) el plugin.
Saludos

**Comment by gonzad26** [comment]
Si queres podes intentar eliminando los siguiente del archivo https://github.com/fedealvz/Woo-iFactura/blob/master/woo-ifactura/admin/class-woo-ifactura-admin.php

Si eliminas el código desde la linea 780 a la 784 inclusive, le quitas el procesamiento de los envíos para ser enviado a iFactura.
https://github.com/fedealvz/Woo-iFactura/blob/7377d39b678b1c726cd3ccf8948905708e61c217/woo-ifactura/admin/class-woo-ifactura-admin.php#L780
https://github.com/fedealvz/Woo-iFactura/blob/7377d39b678b1c726cd3ccf8948905708e61c217/woo-ifactura/admin/class-woo-ifactura-admin.php#L784

Esto no lo pude probar, es por lo que entiendo del código.

**Comment by paulabender** [comment]
Hola Gonzalo! gracias por el dato, comenté esas líneas y parece que va bien. Ahora, tendría que hacerlo cada vez que actualizo el plugin…

Volviendo al tema de poder revisar la factura antes de emitir, me parece importante. Me pasó lo siguiente, tenía un pedido con una parte del pago reembolsado, no me tomó el reembolso y facturó el doble de lo que tenía que ser. Tuve que ingresar a iFactura y generar una nota de crédito para anularla. Ahora, esa factura errónea ya se le envió al cliente automáticamente según entiendo, primer problema, y además, el botón para generar comprobante desde WooCommerce ya me aparece con la flechita verde, sólo puedo ver la factura generada, osea que no puedo generar una nueva factura correcta, tengo que hacerlo a mano, segundo problema.

Comento las experiencias que voy teniendo para que lo consideren.

Saludos y gracias

**Comment by paulabender** [comment]
Y aprovecho para comentar otro tema, es un detalle pero ya que estoy… 
Cuando se aplica algún tipo de descuento, como un cupón, no pone: Valor real - % descuento - Valor final con descuento aplicado. Sino que pone como valor real el valor con el descuento aplicado, y en descuento pone 0%.

**Comment by gonzad26** [comment]
El plugin es solo para facturar, no tiene implementado el tema de notas de crédito y débito. Eso lo debes hacer desde iFactura.
Efectivamente, es para generar un solo comprobante que corresponde a una sola venta o por lo menos en mi experiencia es lo que siempre pude hacer.

Por lo de los descuentos, depende como apliques dichos descuentos. Ya ha habido otros usuarios, también me incluyo, con problemas con algunos plugins de descuento que se hacen cosas raras en las ordenes. Cosas como crear un item negativo hasta crear impuestos negativos para mostrar impactados dichos descuentos. 

Como te decía antes, podes "forkear" el repositorio y adaptar el plugin a tus necesidades como hiciste con el tema del envió. Después cuando tenga alguna actualización el plugin, lo volves a "mergear" y listo.
