### ISSUE TITLE
No se especificó el punto de venta para facturar. Factura con ID 8678

### ISSUE THREAD

**Issue by luisway2net** [fedealvz/Woo-iFactura#22]
No se especificó el punto de venta para facturar. Factura con ID 8678.
En el panel del plugin le especifique el numero 4 y lo guarde. Tambien lo cree en el panel de ifactura y lo puse como predeterminado. Pero igualmente me sale ese mensaje. Estoy probando en modo demo.
Que esta mal?

**Comment by fedealvz** [comment]
Hola @luisway2net en modo demo no estás probando sobre tu cuenta sino sobre la demo de iFactura.
Tenés que pasarlo a modo producción para que use tu cuenta.

**Comment by luisway2net** [comment]
Ok Gracias, lo voy a hacer
