### ISSUE TITLE
Problemas con el IVA

### ISSUE THREAD

**Issue by raeelizalde** [fedealvz/Woo-iFactura#24]
Buenos días, estoy teniendo problemas, al facturar siendo responsable inscripto me factura el total sin impuestos, por lo que la factura me queda con iva pero con el importe total como si no lo hubiera tenido. Necesito solucionarlo

**Comment by gonzad26** [comment]
Hola!
Tenes que configurar el IVA en Woocommerce. Te dejo esta imagen como ejemplo sacada del issue #7 
![image](https://user-images.githubusercontent.com/5983034/95211299-c5e37480-07c2-11eb-8aaa-3ef83c31e814.png)
