### ISSUE TITLE
Problema con el envio automatico

### ISSUE THREAD

**Issue by juanpeluffo** [fedealvz/Woo-iFactura#25]
Buenas tardes! Instalé el plugin hoy y entendí que ante una orden abonada y confirmada debería facturarse automáticamente, pero no fue así. Tuve que entrar a "WooCommerce / Pedidos" y generar los comprobantes manualmente. Esto es correcto? O hay una forma de que se facture automáticamente? Muchas gracias!

**Comment by gonzad26** [comment]
Hola Juan!
Si para facturar siempre lo pude hacer yendo a Pedidos y ahí presionando generar comprobante. Lo que automatiza el plugin es la comunicación y configuración de la información para hacer el comprobante.
