### ISSUE TITLE
Ha ocurrido un error en el procesamiento de la petición. ERROR

### ISSUE THREAD

**Issue by printmza** [fedealvz/Woo-iFactura#26]
Hola me tira el siguient error :  Ha ocurrido un error en el procesamiento de la petición.

En IFACTURA esta todo ok adjunto capturas
¿Que puede estar pasando?

Error de woocommerce > https://www.centralweb.info/home2/wp-content/uploads/2020/10/IFACTURA2.jpg

Ok de ifactura >  https://www.centralweb.info/home2/wp-content/uploads/2020/10/IFACTURA3.jpg

Gracias

**Comment by gonzad26** [comment]
Veo que te falta la dirección de tu cliente por eso te debe estar dando error. Verifica eso. Tendrias que tener algo como el siguiente ejemplo
![image](https://user-images.githubusercontent.com/5983034/95410176-9c793480-08f9-11eb-84c0-e08a4d1cbda3.png)

**Comment by printmza** [comment]
Gracias Gonzalo ya pude, tengo otra duda como puedo para facturar yo desde el backend es decir los campos dni y condicion impositiva no me deja editarlos en woocommerce>>pedidos como los demás campo solo puedo completarlo si hago las compra como un cliente ...tenés idea como puedo habilitar el backend para editar yo ?? Muchísimas gracias

**Comment by gonzad26** [comment]
En el readme del repositorio está todo lo referido a ventas previas al uso del módulo.

**Comment by printmza** [comment]
Gracias ya lo pude hacer funcionar solamente me queda la duda como hago para que la factura aparezca en el area personal del cliente? para que cuando ingrese con su usuario y contraseña pueda descargarla desde su cuenta

GRACIAS POR TODO !!!

**Comment by gonzad26** [comment]
De nada!
En el área de cliente no encontré que tenga links a comprobantes. 
Al ser un módulo de código abierto, podes hacerle la modificación y mostrarlo donde quieras.

Saludos!
