### ISSUE TITLE
Error : INICIO DE SESIÓN INCORRECTO

### ISSUE THREAD

**Issue by MatiasCarr** [fedealvz/Woo-iFactura#27]
Hola configure el plugin pero indica INICIO DE SESIÓN INCORRECTO, estoy poniendo el email en ifactura y su correspondiente contraseña puede ayudarme?

**Comment by gonzad26** [comment]
Hola!
Si tenes un plan contratado y estas usando ese login fijate no tener activado el modo de pruebas

![image](https://user-images.githubusercontent.com/5983034/96623243-77b19380-12e1-11eb-9e69-42515e66bf03.png)
Más información hay en otros issue:  #11 

Saludos!
