### ISSUE TITLE
campo DNI - error

### ISSUE THREAD

**Issue by antocisale** [fedealvz/Woo-iFactura#28]
Trabajo en una página con venta en argentina y al extranjero. En las ventas que se realizan en Argentina, funciona todo perfectamente (las facturas por decisión del dueño de la tienda se hacen manualmente). Pero si un extranjero quiere comprar, y su "dni" tiene letras (me pasa con clientes de Chile), no permite continuar con el método de pago correspondiente.

Por ahí en estos casos convendría agregar una verificación de que, si el país de facturación es Argentina, el input del DNI permita solo numeros, y que si es otro valor el input del DNI acepte otros caracteres... mas que nada para que puedan continuar con el pago desde la página, sin tener que contactarse por privado.

O por ahí se les ocurre otra solución! Por lo demás funciona todo excelente por ahora!

**Comment by gonzad26** [comment]
Hola!

Entiendo que el plugin es orientado al publico Argentino por eso entiendo que es la limitación de caracteres y tipo.
El plugin es de código abierto y podes hacerle la modificación que planteás que me parece una muy buena idea.

Saludos
