### ISSUE TITLE
Consulta

### ISSUE THREAD

**Issue by ismismismx** [fedealvz/Woo-iFactura#29]
Buenas. Se supone que las facturas se emiten solas? Porque hasta ahora sólo funcionó cuando lo hice manualmente apretando el botón. Tengo marcada la opción "enviar automáticamente al cliente". En que plazo de tiempo debería suceder esto ultimo? Gracias desde ya

**Comment by gonzad26** [comment]
Hola!
Los comprobantes los haces mediante ese botón. La opción que decís es para que cuando generás el comprobante se envié por correo electrónico al cliente.

Saludos!
