### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by adriankamena** [fedealvz/Woo-iFactura#3]
Hola! Instalé la actualización. Pero hay un error que me sigue ocurriendo, es "Valor unitario inválido". No tengo nada fuera de lo normal. De hecho hasta ahora pude hacer solo una factura y tiene mas o menos los mismos artículos. Todos valores unitarios enteros. Los dos clientes Consumidor final, o sea sin el cálculo del IVA discriminado. Alguien podría saber de que se trata?
Gracias!

**Comment by gonzad26** [comment]
Te pediría para ver si puedo replicar el problema y ayudarte una captura de pantalla o los valores que estas intentando facturar. 

Hasta el momento no he encontrado ese problema pero quizás sea un problema de valores o cantidades.

**Comment by adriankamena** [comment]
Hola! Ahí te envío las capturas. 
![captura20](https://user-images.githubusercontent.com/54455744/64088482-106d0480-cd18-11e9-853c-4d8559b48cc3.jpg)
![captura21](https://user-images.githubusercontent.com/54455744/64088483-106d0480-cd18-11e9-9e85-8759819aad85.jpg)

**Comment by gonzad26** [comment]
Le encontré la vuelta, el problema esta en el item de valor 0$ que tenes ahi como Retiro en Recoleta.

**Comment by adriankamena** [comment]
Excelente, gracias! 
Gracias fedealvz por la actualización.
Saludos!

**Comment by tiendaupego** [comment]
Buenas, tengo el mismo problema.. como lo solucionaron?

Gracias de antemano!

**Comment by tiendaupego** [comment]
![image](https://user-images.githubusercontent.com/64430847/86146882-1f0a8080-bacf-11ea-8af9-4221aaa608c7.png)

En realidad mi problemas es por el descuento, creo


Gracias

**Comment by gonzad26** [comment]
Parecería que si, tendrías que quitarle el descuento o   podes cambiar la parte que procesa los artículos para que no tome el negativo.

**Comment by tiendaupego** [comment]
Gracias por tu pronta respuesta

El tema que venia funcionando bien...desde que lo instale y la verdad que a los clientes les gusta ver el "numero negativo". Hay forma que actualicen para que funcione como venia funcionando?
Gracias de antemano

**Comment by gonzad26** [comment]
La API de iFactura no soporta valores en 0 o negativos dado que son valores que no son facturables. Por eso te esta fallando.

Además, pensando en el plugin, si es un valor negativo como puede saber el plugin a que valor restarle ese descuento. Porque si tenes varios productos y el descuento es sobre el total de lo que vendiste no se me ocurre como se puede calcular el valor real a facturar de cada item, dado que el descuento puede ser mayor a uno o varios productos y caemos sobre el tema del 0.
Al menos que factures un solo item por el total de la venta con el descuento aplicado.

**Comment by tiendaupego** [comment]
Ok, tengo dos dudas...

Siempre estuvieron los descuentos y no tenia problemas.. Facturaba bien desde woocommerce con este pluging..
Yo no quiero que en la factura salga el descuento.. solo quiero que este en el pedido.

En la factura obviamente es todo positivo... que cambio? o mejor dicho como lo puedo solucionar?

Gracias!

**Comment by gonzad26** [comment]
Compartime una captura de pantalla de una factura emitida y su respectiva orden con un descuento aplicado a ver si se me ocurre que más puede ser.
En cuanto a descuentos de la captura anterior, tendrias que ver la manera que sean sobre los productos en si. O modificar el plugin  para que te haga una factura por el total también podría ser, asi te da siempre positivo.

**Comment by tiendaupego** [comment]
Genial!!! gracias!!!

Ahi va!

![image](https://user-images.githubusercontent.com/64430847/86158273-ef637480-bade-11ea-9162-5f76528ea996.png)

![image](https://user-images.githubusercontent.com/64430847/86158334-030edb00-badf-11ea-8194-1273a1f11302.png)

![image](https://user-images.githubusercontent.com/64430847/86158446-29347b00-badf-11ea-8c3f-2be403b435cd.png)

**Comment by gonzad26** [comment]
Clarisimo ahi si veo el problema. 
![image](https://user-images.githubusercontent.com/5983034/86158714-90eac600-badf-11ea-9cb9-ca0f84baec5a.png)

El descuento por "transferencia bancaria directa" de la primera captura es un elemento global y no tiene forma el sistema de descontarselo a un item en particular por eso le llega a iFactura como negativo. Como un item por separado a facturar.
En cambio en esta captura más reciente el descuento es sobre la "Silla pocket azul", pudiendo calcular el valor final y enviar a iFactura el valor final directamente.

Tendrías que ver la forma de aplicar esos descuentos globales a los productos o la modificación del plugin que te sugerí en el comentario pasado.

**Comment by tiendaupego** [comment]
ahhh ahora entiendo... el plugin de descuentos se actualizo y por eso ahora esta arriba.

Cuando decis modificar el plugin, te referis a este? o se al de uds? si es asi, pasame el costo.

Gracias!

**Comment by gonzad26** [comment]
Solo soy usuario y gran consumidor del plugin, era una sugerencia la modificación del plugin por si te animas a hacerla.. Yo tengo algunos descuentos que no se vieron afectados dado que siguen siendo aplicados sobre los productos.

Al ser un plugin no oficial, hay que esperar que modifiquen este repositorio.

**Comment by tiendaupego** [comment]
ahh gracias!!! pensé que estabas en el equipo! 

Ya que estamos y por ahí me ayudas...Sabes de alguno que aplique al producto y que pueda realizar un descuento segun el medio de pago?

Gracias de antemano
