### ISSUE TITLE
Cambio en la estructura de facturación

### ISSUE THREAD

**Issue by Growlersoficial** [fedealvz/Woo-iFactura#30]
Hola! Estamos teniendo problemas con la conciliación de facturas/pedidos. Quisiéramos que la factura emitida se identifique con el numero de pedido de la pagina vinculada (WooCommerce - IFactura),y el nombre y apellido de la persona para facilitarnos la conciliación.

Desde ya, muchas gracias!

Agustín

**Comment by gonzad26** [comment]
Hola!
En ese caso, al ser un proyecto open source, te recomendaría que modifiques el plugin para realizar esa acción.

Por lo que vi la lógica para hacer el comprobante esta en este archivo https://github.com/fedealvz/Woo-iFactura/blob/master/woo-ifactura/admin/class-woo-ifactura-admin.php

Saludos!

**Comment by Growlersoficial** [comment]
Estimados, este correo es para nosotros?
