### ISSUE TITLE
INIICIO DE SESIÓN FALLIDO

### ISSUE THREAD

**Issue by Motuslibre** [fedealvz/Woo-iFactura#31]
Buen día. Estoy integrando iFactura en wordpress con el plugin que brindan de GitHub pero al querer generar un comprobante me salta un anuncio que dice "error inicio de sesión". El usuario a utilizar sería el mismo de iFactura verdad? Podrían guiarme a saber cuál podría ser el problemar? Gracias

**Comment by gonzad26** [comment]
Hola!

Fijate en las opciones del plugin si lo tenes en modo de pruebas. Porque el modo de pruebas tiene otras creedenciales diferentes a las contratadas.

![image](https://user-images.githubusercontent.com/5983034/107217451-f21b3600-69ec-11eb-8255-2ab83ce4ef96.png)

Más info en otros issues : #27 

Saludos

**Comment by Motuslibre** [comment]
Gracias por responder. Si lo tengo en modo de pruebas exactamente, y qué credenciales debería ingresar? de donde las busco?

**Comment by gonzad26** [comment]
El entorno de pruebas es una demo. Pedila por ticket para podes hacer tus pruebas tranquilo.
