### ISSUE TITLE
Error al intentar facturar

### ISSUE THREAD

**Issue by ignaciospaventa** [fedealvz/Woo-iFactura#32]
Hola, estamos experimentando errores al intentar facturar en woocommerce a través del plugin.

Desde el soporte telefónico nos enviaron lo siguiente:

Desde el visor de eventos se muestra un error en principio deberías verificar Error INVOCANDO al servicio WSAA: Computador no autorizado a acceder al servicio en iFactura

¿Cómo podemos solucionarlo?

**Comment by gonzad26** [comment]
Hola!

Ese error es que te falto hacer algún paso en el alta de iFactura. Te recomiendo seguir la siguiente guía: https://help.wnpower.com/hc/es/articles/360033476571-Error-INVOCANDO-al-servicio-WSAA-Computador-no-autorizado-a-acceder-al-servicio-en-iFactura

Igualmente antes de probar el plugin, te recomendaría que pruebes emitir un comprobante desde iFactura y cuando este todo OK empieces a utilizar el plugin.

Saludos!
