### ISSUE TITLE
Condición IVA Exento

### ISSUE THREAD

**Issue by ignaciospaventa** [fedealvz/Woo-iFactura#34]
Hola, tengo unas consultas respecto del IVA. Nuestro producto es EXCENTO. ¿Como debemos parametrizar el complemento y las tasas impositivas para que lo envíen correctamente? Nos envían lo siguiente del soporte:

_Tomando el ejemplo de la Factura A 0003 - 00000001 lo que pasa es que esta enviando mal el tipo de alicuota IVA que informa a iFactura para que no se no gravado.

Envió:
Linea 1: Gardenista Valor ($) : 7300 IVA ($): 0 IVA(%): 0 ID de IVA según documentación de API: 1
Linea 2: Moto Valor ($) : 250 IVA ($): 52.50 IVA(%): 21 ID de IVA según documentación de API: 3

Con el ID de tipo de IVA 1 es un IVA 0% no es exento ni no gravado. Esos tipos de IVA tienen sus propios IDs que son:
7 Exento
8 No Gravado

Tendrías que revisar los datos que envía a iFactura para que el tipo de IVA informado sea el correcto._

Aguardo su respuesta

Gracias

**Comment by villaboamiguel** [comment]
Hola!

Entiendo entonces que vendes productos que son de IVA exento? Según la documentación de la API de iFactura son tipos de IVA que soporta la aplicación pero en este módulo no los encontré.

Por lo que vi del código quizás tengas que adaptar el módulo para la condición de IVA puntual que tenés porque no encontré nada referido a exento.

También pude ser una buena idea de dejar este issue como nota para que se agregue dicha funcionalidad para una futura mejora que lance el desarrollador. 

Saludos.
