### ISSUE TITLE
No puedo editar los campos de pedidos anteriores a tener activado el plugin

### ISSUE THREAD

**Issue by raeelizalde** [fedealvz/Woo-iFactura#35]
Hola, por un problema desactive por unos días el plugin, al intentar facturar no puedo hacerlo ya que aun editando el pedido no me deja cambiar la condicion de iva ni la personeria
![Captura2](https://user-images.githubusercontent.com/32419343/120242710-f25d6c80-c23b-11eb-8cf0-fe2d0e9dce6f.PNG)
Alguna opción?

**Comment by villaboamiguel** [comment]
Hola!
Al tratarse de campos que no son propios de Woocommerce eso se edita de otra manera. Es algo que ya había leído en otro issue: 
https://github.com/fedealvz/Woo-iFactura/issues/2#issuecomment-524557226
Fijate si te sirve para completar los datos faltantes.

Saludos

**Comment by raeelizalde** [comment]
el tema es completarlo para 400 pedidos, imposible hacerlo ayer para cerrar el mes
