### ISSUE TITLE
Problemas con dato que no llega en el array. class-wp-wook linea 294

### ISSUE THREAD

**Issue by Ch1v4** [fedealvz/Woo-iFactura#36]
Hola como va, excelente plugin la verdad es que facilita mucho para el tema de la facturación desde woocommerce.

Tengo un problema desde que lo instale y es que en el mail de pedido procesado llega el siguiente error:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Woo_iFactura_Admin' does not have a method 'woo_ifactura_display_tipopersona_in_email_fields' in /home/midominio.com/wp-includes/class-wp-hook.php on line 294

Entiendo que no esta llegando un valor al array ¿es correcto? ¿como puedo evitar que se imprima en el mail este error o detectar que dato esta faltando?

Desde ya muchas gracias.

**Comment by villaboamiguel** [comment]
Hola!

Hay toda una conversación en un issue al respecto: https://github.com/fedealvz/Woo-iFactura/issues/33
Capaz te sirve.

Saludos!

**Comment by Ch1v4** [comment]
Excelente! se me paso ese issue gracias @villaboamiguel
