### ISSUE TITLE
Problema con leguaje mostrado

### ISSUE THREAD

**Issue by raeelizalde** [fedealvz/Woo-iFactura#4]
Hola, el plugin me esta mostrando los textos en ingles en el checkout, como lo puedo solucionar? Ademas estaria bueno que trajera por defecto la personería y el tipo de impuesto para no tardar mas al hacer la carga de la compra.

https://drive.google.com/open?id=1GDef3WIH-o9uVfQ0NyD-K0aC1zGJI44K

**Comment by raeelizalde** [comment]
Ya lo solucioné editando yo a mano, quedaron fijos los textos pero funciona bien, de la otra forma con las traducciones no funcionaba.
https://drive.google.com/file/d/1HoiJTm8Cw7OBtPmhzH7E2POtLzZo8J1x/view?usp=sharing

**Comment by gonzad26** [comment]
Hola! Te hago una consulta de curioso, yo lo tengo instalado en un Wordpress y no tuve problemas con el idioma. Estoy pensando en instalarlo en otro.

Te consulto, en que idioma tenes instalado Wordpress y Woocommerce? es_ES?

Gracias

**Comment by raeelizalde** [comment]
Si, tengo todo en español , vi los archivos de lenguaje pero no me los
carga y por lo que vi a otros tampoco. Fuera de eso el tema de que cargue
por default las opciones de Categ de iva y personería para mi son
fundamentales, incluso si se pudieran sacar mejor porque sumar datos a
ingresar hace que pierdas gente por el camino. Te dejo mi web, fijate que
esta todo en español. Dentro del admin esta como español seleccionado.
Saludos

https://hurraweb.com/
