### ISSUE TITLE
Error "The CondicionImpositiva field is required."

### ISSUE THREAD

**Issue by MaritoCe** [fedealvz/Woo-iFactura#5]
Hola! Ya tengo habilitada la cuenta e instalado el plugin en mi sitio web con Woocommerce. Entiendo que para emitir los comprobantes lo debo hacer desde "Generar comprobante" en el listado de pedidos, no? Ahora bien, me aparece el siguiente mensaje con los pedidos viejos, porque se ve que es un campo que agrega el plugin y no fue llenado por los clientes antes de instalarlo:

"The CondicionImpositiva field is required."

Hay alguna forma de salvar este error? Porque desde el administrador no me deja modificar este campo.

Por otro lado, quería saber dónde configuro el sistema para que todas las facturas las genere como "tipo: servicio".

Muchas gracias!
Saludos.

**Comment by gonzad26** [comment]
Hola! Como estas?

Eso me sucedio cuando quise facturar ordenes anterior a usar el plugin de iFactura.

En este post puse como lo solucione, espero que te sirva: https://github.com/fedealvz/Woo-iFactura/issues/2#issuecomment-524557226 

Saludos!

**Comment by MaritoCe** [comment]
Gracias Gonza! Lo miro.

Saludos!
