### ISSUE TITLE
Problemas con el IVA

### ISSUE THREAD

**Issue by germanrandazzo** [fedealvz/Woo-iFactura#7]
Buenas tardes, trabajamos con un sitio web mayorista por lo que nuestros precios no llevan IVA incluido. Por lo que estamos teniendo problemas a la hora de generar facturas, ya que el plugin le resta al valor de cada producto un supuesto "IVA" que no tienen incluido. Esto hace que nuestras facturas terminen no incluyendo IVA en su valor final. Tenemos manera de evitar que esto suceda.

En los ejemplos que adjunto podrán ver cual debería ser el valor real de la factura, y cual es el resultado en el comprobante.

![Screen Shot 2020-01-21 at 15 09 59](https://user-images.githubusercontent.com/60151893/72830776-36138f80-3c60-11ea-8d06-61c9ee29445e.jpg)
![Screen Shot 2020-01-21 at 15 10 09](https://user-images.githubusercontent.com/60151893/72830783-3a3fad00-3c60-11ea-8431-cd6f5445bbb7.jpg)

Muchas gracias.

**Comment by fedealvz** [comment]
Hola @germanrandazzo gracias por reportarlo! Podrías adjuntar acá una captura de la configuración del IVA de tu WooCommerce así lo revisamos? Saludos!

**Comment by germanrandazzo** [comment]
Hola Federico, muchas gracias por tu respuesta. Te adjunto captura de la configuración en la sección de impuestos de nuestro woocommerce. Espero sea de ayuda, cualquier otra duda que tengas pregúntame tranquilo. Saludos.






    Germán Randazzo
     Diseñador Senior
   --
      Estudio: 11-2153-2352 <tel:11-2153-2352>
      Celular: 15-6205-8873 <tel:15-6205-8873>

**Comment by fedealvz** [comment]
@germanrandazzo upss creo que no se adjuntó la captura

**Comment by germanrandazzo** [comment]
Te las mando en un ZIP porque el programa de mails de la Mac siempre adjunta cualquier cosa. Avisame si están OK




    Germán Randazzo
     Diseñador Senior
   --
      Estudio: 11-2153-2352 <tel:11-2153-2352>
      Celular: 15-6205-8873 <tel:15-6205-8873>

**Comment by fedealvz** [comment]
@germanrandazzo tampoco... fijate si podés contestar el Issue online en https://github.com/fedealvz/Woo-iFactura/issues/7

**Comment by germanrandazzo** [comment]
Hola Federico, muchas gracias por tu respuesta. Te adjunto captura de la configuración en la sección de impuestos de nuestro woocommerce. Espero sea de ayuda, cualquier otra duda que tengas pregúntame tranquilo. Saludos.
![Screen Shot 2020-01-23 at 13 49 04](https://user-images.githubusercontent.com/60151893/73012987-2c239500-3df6-11ea-87e4-55feb8080aaf.jpg)
![Screen Shot 2020-01-23 at 13 49 28](https://user-images.githubusercontent.com/60151893/73012988-2cbc2b80-3df6-11ea-8550-7bd90ca89c4a.jpg)

**Comment by fedealvz** [comment]
Ahora si 👍 Gracias! Vamos a revisar el plugin con esa configuración y apenas tenga noveades te aviso por acá. Saludos!

**Comment by germanrandazzo** [comment]
Buen día. Tenemos alguna novedad con respecto a el tema? Muchas gracias.



    Germán Randazzo
     Diseñador Senior
   --
      Estudio: 11-2153-2352 <tel:11-2153-2352>
      Celular: 15-6205-8873 <tel:15-6205-8873>

**Comment by fedealvz** [comment]
Hola @germanrandazzo !!! Ahí publicamos update, por favor descargalo de nuevo y fijate ahora. Espero tu feedback! Saludos

**Comment by germanrandazzo** [comment]
Excelente, lo voy a probar. Muchas gracias por el soporte y la buena predisposición.
