### ISSUE TITLE
Falla 

### ISSUE THREAD

**Issue by Bikiny** [fedealvz/Woo-iFactura#8]
descargue el plugin pero no puedo instalarlo .

leyenda: 
Instalando plugin desde el archivo: Woo-iFactura-master (1).zip
Descomprimiendo…

Instalando el plugin…

No se ha podido descomprimir el paquete. No se encontraron plugins.

La instalación del plugin ha fallado.

Volver al instalador de plugins

**Comment by fedealvz** [comment]
Hola @Bikiny seguramente estés subiendo el ZIP tal cual lo descargás de Github y en realidad tenés que subir sólo la carpeta que viene adentro.

Por favor seguí estas instrucciones: https://github.com/fedealvz/Woo-iFactura#instalaci%C3%B3n
