### ISSUE TITLE
No puedo activar IFactura en Woocommerce

### ISSUE THREAD

**Issue by Paulavcano** [fedealvz/Woo-iFactura#9]
Buen dia, tengo un issue con la emisión de factura en woocommerce. Tengo el mismo usuario de factura funcionando bien en tienda nube sin problemas pero en woocommerce no emite la factura. Además de la configuración dei factura en Woocommerce/ajustes hace falta alguna validación adicional para que funcione la integración? Gracias!

**Comment by gonzad26** [comment]
Si configuraste todos los parámetros debería funcionar. Generalmente cuando tiene un problema de comunicación o de algo, el plugin te avisa con un banner amarillo al momento de facturar.

Si esto no te pasa, podrías ver si te dice algo la consola del chrome (o el navegador que utilices)?  A ver si te puedo dar una mano.

Saludos!
